# Generated by Django 3.1 on 2020-09-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created_date',
            new_name='c_created_date',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='c_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='published_date',
            new_name='c_published_date',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='c_text',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='title',
            new_name='c_title',
        ),
    ]
