# Generated by Django 3.1 on 2020-09-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200903_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='c_id',
            new_name='c_author',
        ),
    ]
